name: tugas_1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter
  flutter_image_compress: ^1.1.0
  get: 4.6.6
  http: ^0.13.5
  image_cropper: ^1.5.1
  image_picker: ^0.8.5+3
  webview_flutter: ^4.0.10
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
